import { Poppins } from "next/font/google";
import "./globals.css";

import Navbar from "./components/Navbar";
import { ClerkProvider} from '@clerk/nextjs'
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import Footer from "./components/Footer";
import Provider from "./storeProvider";
import Message from "./Message";


const poppins = Poppins({ 
  subsets: ["latin"],
  weight  : ['400','500','600','700','800']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        
    <Provider>


    <ClerkProvider>
    <html lang="en">
      <body className={poppins.className}>
      <Message>
        <Navbar/>

        {children}
      
        <Footer/>
      </Message>
        </body>
    </html>
    </ClerkProvider>
    </Provider>
      
        
  );
}
